### ISSUE TITLE
quickResolveConflict   does not always complete

### ISSUE THREAD

**Issue by pauljohnleonard** [fintechneo/angular-git-filebrowser#4]
I expected quickResolveConflict to complete. I had to add the take(1)  in order for my for forkJoin to finish.   Is this the intended behaviour?

```
 const olist = this.data.files.map(file => this.data.backend.quickResolveConflict(file, pick).pipe(take(1)));

        forkJoin(olist).subscribe( () => {
               this.data.backend.markConflictsResolved().subscribe( () => this.dialogRef.close())
           }    
        )
```

**Comment by petersalomonsen** [comment]
No not intended. I believe we want to fix this.

**Comment by petersalomonsen** [comment]
Fixed here: https://github.com/petersalomonsen/angular-git-filebrowser/commit/f0b08ed04153c13e4550a1da3d4b9f9961eba5a6#diff-1e9cda227ed008141964ec146f53d45cR213
